import api from './api';
import {Asset} from 'react-native-image-picker';

export interface MediaItem {
  _id: string;
  s3Url: string;
  mimeType: string;
  sizeBytes: number;
  originalName: string;
}

export const mediaService = {
  async upload(
    asset: Asset,
    onUploadProgress?: (progressEvent: any) => void,
    signal?: AbortSignal,
  ): Promise<MediaItem> {
    const formData = new FormData();

    const uri = asset.uri || '';
    const filename = asset.fileName || uri.split('/').pop() || 'upload';
    const type = asset.type || 'image/jpeg';

    formData.append('file', {
      uri,
      name: filename,
      type,
    } as any);

    try {
      const response = await api.post('/api/v1/media/upload', formData, {
        headers: {'Content-Type': 'multipart/form-data'},
        timeout: 120000, // 2 min for large files
        onUploadProgress,
        signal,
      });
      return response.data.data;
    } catch (e: any) {
      if (e.name === 'CanceledError' || e.code === 'ERR_CANCELED') {
        console.log('[MediaService] Upload cancelled');
      } else {
        const errMsg = e.response?.data?.message || e.message;
        console.error('[MediaService] Upload failed:', errMsg);
      }
      throw e;
    }
  },

  // Upload from a bare file path (e.g. thumbnail generated by react-native-create-thumbnail)
  async uploadFromPath(
    filePath: string,
    mimeType = 'image/jpeg',
    onUploadProgress?: (progressEvent: any) => void,
    signal?: AbortSignal,
  ): Promise<MediaItem> {
    const formData = new FormData();
    const filename = filePath.split('/').pop() || 'thumbnail.jpg';
    formData.append('file', { uri: filePath, name: filename, type: mimeType } as any);
    try {
      const response = await api.post('/api/v1/media/upload', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
        timeout: 60000,
        onUploadProgress,
        signal,
      });
      return response.data.data;
    } catch (e: any) {
      if (e.name === 'CanceledError' || e.code === 'ERR_CANCELED') {
        console.log('[MediaService] Thumbnail upload cancelled');
      } else {
        console.error('[MediaService] Thumbnail upload failed:', e?.response?.data?.message || e.message);
      }
      throw e;
    }
  },

  async delete(mediaId: string): Promise<void> {
    await api.delete(`/api/v1/media/${mediaId}`);
  },
};
